---
driver: 
  name: vagrant

platforms:
- name: centos-5.9

- name: centos-6.4

- name: debian-7.1
  run_list:
    - recipe[apt]

- name: ubuntu-10.04
  run_list:
  - recipe[apt]

- name: ubuntu-12.04
  run_list:
  - recipe[apt]

- name: ubuntu-14.04
  run_list:
  - recipe[apt]

suites:
- name: default
  run_list:
  - recipe[minitest-handler]
  - recipe[tftp_test::default]
  attributes: {}
